### ISSUE TITLE
magnitude_to_countrate function

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [spacetelescope/jwst-fgs-countrate#3]
To support mirage simulations it would be handy to be able to import a magnitude_to_countrate function from this package.

The use within mirage would be here:
https://github.com/spacetelescope/mirage/blob/6c8257461bfe77d27c234227a8ea5278b5cb6f46/mirage/utils/utils.py#L286

with the following scenario: a user submits a catalog with `fgs1_magnitude` or `fgs2_magnitude` , then mirage applies the appropriate transformation to countrate imported from jwst-fgs-countrate.

A consequence of implementing this would be that  jwst-fgs-countrate has to be publicly available.

**Comment by shanosborne** [comment]
Done in #15
